version: '3.8'

services:
  # Backend API
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./model.joblib:/app/model.joblib
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network
    environment:
      - PYTHONUNBUFFERED=1

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=/api
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:
    driver: bridge 